[project]
name = "make-epub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "css-inline>=0.17.0",
    "pandoc>=2.4",
    "pandoc-latex-environment>=1.2.1.0",
]
